Document: amap
Title: Debian amap Manual
Author: <insert document author here>
Abstract: This manual describes what amap is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/amap/amap.sgml.gz

Format: postscript
Files: /usr/share/doc/amap/amap.ps.gz

Format: text
Files: /usr/share/doc/amap/amap.text.gz

Format: HTML
Index: /usr/share/doc/amap/html/index.html
Files: /usr/share/doc/amap/html/*.html
